#!/bin/bash
#
# k8sEasy2
#

echo "---------------------------------------------- Installing Flannel network"
kubectl delete podsecuritypolicy psp.flannel.unprivileged
kubectl delete ClusterRole flannel
kubectl delete ClusterRoleBinding flannel
kubectl delete ServiceAccount flannel -n kube-system
kubectl delete ConfigMap kube-flannel-cfg -n kube-system
kubectl delete DaemonSet kube-flannel-ds-amd64 -n kube-system
kubectl delete DaemonSet kube-flannel-ds-arm64 -n kube-system
kubectl delete DaemonSet kube-flannel-ds-arm -n kube-system
kubectl delete DaemonSet kube-flannel-ds-ppc64le -n kube-system
kubectl delete DaemonSet kube-flannel-ds-s390x -n kube-system
kubectl apply -f $(dirname "$0")/kube-flannel.yml
