#!/bin/bash

echo "---------------------------------------------- Installing Helm and Tiller"
# try remove clusterRoleBinding and respective tiller serviceaccount
kubectl delete clusterrolebinding tiller
kubectl delete serviceaccount tiller -n kube-system

#Create the tiller serviceaccount:
kubectl -n kube-system create serviceaccount tiller

#Next, bind the tiller serviceaccount to the cluster-admin role:
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller

# install helm3
curl -fsSLJ -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get
chmod 700 get_helm.sh
./get_helm.sh
rm ./get_helm.sh
helm init
# PATCH4: Error: configmaps is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
# perception: seams helm2 serviceAccount change from "system:serviceaccount:kube-system:default" to "tiller"
kubectl --namespace kube-system patch deploy tiller-deploy -p '{"spec":{"template":{"spec":{"serviceAccount":"tiller"}}}}'

# add repository on our cluster
helm repo add stable https://kubernetes-charts.storage.googleapis.com/
helm repo update
